export const categoryEmoji: Record<string, string> = {
  // Groceries
  'Coffee': '☕',
  'Chicken': '🍗',
  'Mince / Meat': '🥩',
  'Fresh cream': '🥛',
  'Eggs': '🥚',
  'Pasta': '🍝',
  'Rice': '🍚',
  'Bread': '🍞',
  'Aromat': '🧂',
  'Mayonnaise': '🫙',
  'Peanut butter': '🥜',
  'Spring onion': '🌿',
  'Coriander': '🌿',
  'Parsley': '🌿',
  'Pepper corns': '🫙',
  'Chillies': '🌶️',
  'Coconut milk': '🥥',
  'Stock cubes': '🧊',
  'Brown onion spice': '🧂',
  'Ground ginger spice': '🫚',
  'Strawberry jam': '🍓',
  'Mushrooms': '🍄',
  'Peppers': '🫑',
  'Mixed fruit jam': '🍇',
  'Butter': '🧈',
  'Noodles': '🍜',
  'Water': '💧',
  'Tuna': '🐟',
  'Tinned fish': '🐟',
  'Tomato paste': '🍅',
  'Onions': '🧅',
  'Potatoes': '🥔',
  'Cheese': '🧀',
  'Cooking oil': '🫙',
  'Milk': '🥛',
  'Drain cleaner': '🧴',
  'Crushed chillies': '🌶️',
  'Dry cook in sauce': '🫙',
  'Stir fry veggies': '🥦',
  'Mixed veggies': '🥗',
  'Red kidney beans': '🫘',
  'Red lentils': '🫘',
  'Chicken liver': '🍗',
  'Cigarettes': '🚬',
  'Dishwashing sponges': '🧽',
  'Sweet treat': '🍬',
  // Toiletries
  'Shaving blades': '🪒',
  'Nivea body cream': '🧴',
  'Nivea men shower gel': '🚿',
  'Nivea men deo spray': '💨',
  'Comfort laundry detergent': '🧺',
  'OSH body wash': '🛁',
  'Handwash': '🧼',
  'Toilet paper': '🧻',
  'Toothpaste': '🦷',
  'Flushable wet wipes': '🧻',
  'Handy Andy': '🧹',
  'Cotton pads': '🩹',
  'Curl product / Treatment': '💆',
  'Head and Shoulders': '🚿',
};

export const defaultEmoji = '🛒';
